### ISSUE TITLE
Leaked MongoDB login

### ISSUE THREAD

**Issue by Darker-Ink** [keannyooi/cloned-drives#1]
You are guys are dumb, You leaked your mongo db login https://github.com/keannyooi/cloned-drives/blob/master/index.js#L31

**Comment by Darker-Ink** [comment]
![image](https://user-images.githubusercontent.com/45852757/126915557-d59a6d9a-83de-476d-aa55-ce794a86bbf7.png)

**Comment by Darker-Ink** [comment]
:/

**Comment by Darker-Ink** [comment]
Reset the password :lmao: Who tf knows how long you have had it in there

**Comment by Darker-Ink** [comment]
and use .env lmao

**Comment by Bnuuy-chan** [comment]
Hello, Thank you for bringing this to our attention
our team will look into it shortly 
- Bnuuy

**Comment by keannyooi** [comment]
i'm sorry, i'm a big idiot indeed

**Comment by keannyooi** [comment]
it's fixed btw
